#!/bin/sh

###############################################################################
#
#  @file       edistro
#  @brief      Creates update package from input directory
#
#  @usage:     1) Create the "eupdate" folder in your working directory. Copy
#                 all your update contents and the "manifest" file into
#                 "eupdate".
#              2) Run "./edistro WORKDIR".
#              3) If success, then the update file eupdate.epd is located in
#                 your working directory.
#
#  @remarks:   * Strongly recommended to use #!/bin/sh instead of bash or other
#                shells. Bash is more relaxed and provides more functionality,
#                but this functionality on the other hand often doesn't even
#                work reliably accross different bash versions!
#
#              * Validator for shell scripting: http://www.shellcheck.net.
#
#              * To deploy the eupdate script to ./test/eupdate/etc/eupdate
#                run ./edistro WORKDIR --deploy
#
#              * If update should also remove a file from the destination, then
#                such file should be created in the update dir with the special
#                suffix ".eremove", e.g. "chmod.eremove" to remove "chmod".
#
#  @copyright  Elnico Ltd. All rights reserved.
#  @author     Jan Kubiznak <kubiznak.jan@elnico.cz>
#
#  @version    1.2 2015-04-03: Jan Kubiznak <kubiznak.jan@elnico.cz>
#                              Busybox fully compatible version (POSIX sh
#                              compatible).
#
#  @version    1.1 2015-03-22: Jan Kubiznak <kubiznak.jan@elnico.cz>
#                              Release version (tested on VF6).
#
#  @version    1.0 2015-03-15: Jan Kubiznak <kubiznak.jan@elnico.cz>
#                              Initial revision.
#
################################################################################
# Return codes

EXIT_SUCCESS=0
EXIT_ERROR_WRONG_PARAMETERS=1
EXIT_ERROR_CD_WORKDIR=2
EXIT_ERROR_NO_EUPDATE=3
EXIT_ERROR_CREATE_TGZ=4
EXIT_ERROR_CALC_MD5=5
EXIT_ERROR_CREATE_EPD=6
EXIT_ERROR_CLEAN_TMP=7

################################################################################
# Init

tool=$(readlink -f "$0")
tooldir=$(dirname "$tool")
workdir=$1

name=eupdate
dir=$name
tgz=$name.tgz
md5=$name.md5
epd=$name.epd

################################################################################

if [ $# -eq 0 ]; then
  echo "Please specify the work directory. Exiting."
  exit $EXIT_ERROR_WRONG_PARAMETERS
fi

echo "Changing dir to $workdir"
cd "$workdir"
if [ "$?" -ne 0 ]; then
  echo "Error: Cannot change directory to $workdir. Exiting..."
  exit $EXIT_ERROR_CD_WORKDIR
fi

test -d "$dir"
if [ "$?" -ne 0 ]; then
  echo "Error. Directory $workdir/$dir does not exist. Exiting..."
  exit $EXIT_ERROR_NO_EUPDATE
fi

if [ "$2" = "--deploy" ]; then
  test -d "$dir/etc/eupdate"
  if [ "$?" -eq 0 ]; then
    echo "Updating the eupdate tool"
    cp "$tooldir/eupdate" "$dir/etc/eupdate/"
  fi
fi

echo "Archiving $dir to $tgz"
tar -czf "$tgz" "$dir"
if [ "$?" -ne 0 ]; then
  echo "Error: Archiving failed. Exiting..."
  exit $EXIT_ERROR_CREATE_TGZ
fi

echo "Calculating MD5 checksum for $tgz"
md5sum -t "$tgz" > "$md5"
if [ "$?" -ne 0 ]; then
  echo "Error: MD5 calculation failed. Exiting..."
  exit $EXIT_ERROR_CALC_MD5
fi

echo "Creating distribution file $epd"
tar -czf "$epd" "$tgz" "$md5"
if [ "$?" -ne 0 ]; then
  echo "Error: Distribution file creation failed. Exiting..."
  exit $EXIT_ERROR_CREATE_EPD
fi

echo "Removing temporary files"
rm "$tgz" "$md5"
if [ "$?" -ne 0 ]; then
  echo "Error: Temporary files removal failed. Exiting..."
  exit $EXIT_ERROR_CLEAN_TMP
fi

echo "Success. Exiting edistro..."
exit $EXIT_SUCCESS

################################################################################
